title = "Tippecanoe County 4-H Fair"
theme = ["dot-org-hugo-theme"]
languageCode = "en-us"
defaultContentLanguage = "en"
timeZone = "America/New_York"
summaryLength = 70
pagination.pagerSize = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[privacy]
  [privacy.youtube]
    privacyEnhanced = true
  [privacy.vimeo]
    enableDNT = true

[permalinks]
    blog = "/blog/:year/:month/:day/:contentbasename/"

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"

